<?php
require __DIR__.'/../common/header.phtml';
require __DIR__.'/../common/topnavbar.phtml';
require __DIR__.'/../common/messages.phtml';
?>

    <form action="/auth/forgotpassword" method="post">
        <div class="container">
            <label for="email"><b>Email</b></label>
            <input type="email" placeholder="Enter your email" name="email" required>

            <input type="submit" name="submit" value="Reset" class="btn">
        </div>
    </form>

<?php
require __DIR__.'/../common/footer.phtml';
?>