<?php
require __DIR__.'/../common/header.phtml';
require __DIR__.'/../common/topnavbar.phtml';
require __DIR__.'/../common/messages.phtml';
?>

<form class="col-lg-6 offset-lg-3" action="/auth/forgotpassword" method="post">
    <div class="form-row">
        <div class="col-md-4 mb-3">
            <label for="email"><b>Email</b></label>
            <input type="email" placeholder="Enter your email" name="email" required>

            <input type="submit" name="submit" value="Reset" class="btn">
        </div>
    </div>
</form>

<?php
require __DIR__.'/../common/footer.phtml';
?>