<?php
require __DIR__.'/../common/header.phtml';
require __DIR__.'/../common/topnavbar.phtml';
?>

<form action="" method="post">
    <div class="container">
        <?php   if (!empty($errors)) {
            foreach ($errors as $error) {
                ?>
                <p><?= $error ?></p>
                <?php
            }
        } ?>
        <label for="uname"><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="username" required>

        <label for="psw"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="password" required>

        <button type="submit">Login</button>
        <label>
            <input type="checkbox" checked="checked" name="remember"> Remember me
        </label>
    </div>

    <div class="container" style="background-color:#f1f1f1">
        <button type="button" class="cancelbtn">Cancel</button>
        <span class="psw">Forgot <a href="#">password?</a></span>
    </div>
</form>

<table>
    <tr>
        <th>baseUrl<th/>
        <td>http://localhost:8080/<td/>
    <tr/>
    <tr>
        <th>ip<th/>
        <td>172.20.0.1<td/>
    <tr/>
    <tr>
    <tr>
        <th>userSession<th/>
        <td>id<td/>
        <td>1<td/>
    <tr/>
    <tr>
        <th><th/>
        <td>username<td/>
        <td>pancho<td/>
    <tr/>
    <tr>
        <th><th/>
        <td>email<td/>
        <td>psabev@parachut.com<td/>
    <tr/>
    <tr>
        <th><th/>
        <td>first_name<td/>
        <td>Pancho<td/>
    <tr/>
    <tr>
        <th><th/>
        <td>last_name<td/>
        <td>Sabev<td/>
    <tr/><tr>
        <th><th/>
        <td>created_at<td/>
        <td>2022-07-21 11:28:00<td/>
    <tr/><tr>
        <th><th/>
        <td>updated_at<td/>
        <td>2022-07-21 11:28:00<td/>
    <tr/><tr/>
<table/>

<?php
require __DIR__.'/../common/footer.phtml';
?>







