<?php
require __DIR__.'/../common/header.phtml';
require __DIR__.'/../common/topnavbar.phtml';
?>

<form action="" method="post">
    <div class="container">
        <?php   if (!empty($errors)) {
            foreach ($errors as $error) {
                ?>
                <p><?= $error ?></p>
                <?php
            }
        } ?>
        <label for="uname"><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="username" required>

        <label for="psw"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="password" required>

        <input type="submit" name="submit" value="Login" class="btn">
    </div>
</form>

<?php
require __DIR__.'/../common/footer.phtml';
?>







