<?php
require __DIR__.'/../common/header.phtml';
require __DIR__.'/../common/topnavbar.phtml';
require __DIR__.'/../common/messages.phtml';
?>

<form action="" method="post">
    <div class="container">
        <label for="uname"><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="username" required>

        <label for="psw"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="password" required>

        <input type="submit" name="submit" value="Login" class="btn">

        <p>Forgot Password?<a href="/auth/forgotpassword"> Click here.</a></p>
        <p>Don't have an account?<a href="/auth/register"> Sign Up.</a></p>
    </div>
</form>

<?php
require __DIR__.'/../common/footer.phtml';
?>







