<?php
require __DIR__.'/../common/header.phtml';
require __DIR__.'/../common/topnavbar.phtml';
?>
<form action="" method="post">
    <div class="container" style="padding: 0 300px">
        <div class="shadow px-5 rounded bg-transparent" style="margin: 100px 0 140px 0">
            <h2 class="py-4">Sign Up</h2>

            <div class="input-group form-group mb-4">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-warning"><i class="fas fa-user"></i></span>
                </div>
                <?php if (!empty($errors['username'])) : ?>
                    <input class="form-control is-invalid" type="text" placeholder="Enter Username" name="username" required>
                <?php endif; ?>
                <?php if (empty($errors['username'])) : ?>
                    <input class="form-control" type="text" placeholder="Enter Username" name="username" value="<?= $data['username'] ?>" required>
                <?php endif;
                if (!empty($errors['username'])) : ?>
                <div class="invalid-feedback">
                    <?=$errors['username']?>
                </div>
                <?php endif; ?>
            </div>

            <div class="input-group form-group mb-4">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-warning"><i class="fas fa-envelope"></i></span>
                </div>
                <?php if (!empty($errors['email'])) : ?>
                    <input class="form-control is-invalid" type="email" placeholder="Enter Email" name="email" required>
                <?php endif; ?>
                <?php if (empty($errors['email'])) : ?>
                    <input class="form-control" type="email" placeholder="Enter Email" name="email" value="<?= $data['email'] ?>" required>
                <?php endif;
                if (!empty($errors['email'])) : ?>
                    <div class="invalid-feedback">
                        <?=$errors['email']?>
                    </div>
                <?php endif; ?>
            </div>

            <div class="input-group form-group mb-4">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-warning"><i class="fas fa-lock"></i></span>
                </div>
                <?php if (!empty($errors['password'])) : ?>
                    <input class="form-control is-invalid" type="password" placeholder="Enter Password" name="password" required>
                <?php endif; ?>
                <?php if (empty($errors['password'])) : ?>
                    <input class="form-control" type="password" placeholder="Enter Password" name="password" required>
                <?php endif;
                if (!empty($errors['password'])) : ?>
                    <div class="invalid-feedback">
                        <?=$errors['password']?>
                    </div>
                <?php endif; ?>
            </div>

            <div class="input-group form-group mb-4">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-warning"><i class="fas fa-key"></i></span>
                </div>
                <?php if (!empty($errors['repeatPass'])) : ?>
                    <input class="form-control is-invalid" type="password" placeholder="Repeat your password" name="repeat_password" required>
                <?php endif; ?>
                <?php if (empty($errors['repeatPass'])) : ?>
                    <input class="form-control" type="password" placeholder="Repeat your password" name="repeat_password" required>
                <?php endif;
                if (!empty($errors['repeatPass'])) : ?>
                    <div class="invalid-feedback">
                        <?=$errors['repeatPass']?>
                    </div>
                <?php endif; ?>
            </div>

            <div class="form-group">
                <div class="custom-control custom-checkbox mr-sm-2 mb-4">
                    <?php if (empty($errors['terms'])) : ?>
                        <input class="custom-control-input " type="checkbox" name="terms" value="1" id="invalidCheck3" required>
                    <?php endif; ?>
                    <?php if (!empty($errors['terms'])) : ?>
                        <input class="custom-control-input is-invalid" type="checkbox" name="terms" value="1" id="invalidCheck3" required>
                    <?php endif; ?>
                    <label class="custom-control-label" for="invalidCheck3">I agree all statements in <a class="text-info text-decoration-none" href="#">Terms of service</a></label>
                    <?php if (!empty($errors['terms'])) : ?>
                    <div class="invalid-feedback">
                        <?=$errors['terms']?>
                    </div>
                    <?php endif; ?>
                </div>
            </div>

            <div class="d-flex justify-content-between mb-4">
                <div>
                    <button class="btn btn-info px-4" type="submit">Register</button>
                </div>
            </div>
            <div class="text-center pb-4">
                <span>I have an account? <a class="text-info text-decoration-none" href="<?= $url ?>auth/login">Sign In</a></span>
            </div>
        </div>
    </div>
</form>


<?php
require __DIR__.'/../common/footer.phtml';
?>