<?php
require __DIR__.'/../common/header.phtml';
require __DIR__.'/../common/topnavbar.phtml';
require __DIR__.'/../common/messages.phtml';

var_dump($class, $errors);
?>

<form action="" method="post">
    <fieldset>
        <legend>Sign Up Form:</legend>
        <div class="form-row">
            <div class="col-md-4 mb-3">
                <label for="first_name"><b>First Name</b></label>
                <input <?= $class['first_name'] ?> type="text" name="first_name" id="first_name" required>
                <div class="invalid-feedback">
                    <?= $errors['first_name'] ?>
                </div>
            </div>
            <div class="col-md-4 mb-3">
                <label for="last_name"><b>Last Name</b></label>
                <input <?= $class['last_name'] ?> type="text" name="last_name" id="last_name" required>
                <div class="valid-feedback">
                    Looks good!
                </div>
                <div class="invalid-feedback">
                    <?= $errors['last_name'] ?>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-4 mb-3">
                <label for="username"><b>Username</b></label>
                <input <?= $class['username'] ?> type="text" name="username" id="username" required>
                <div class="invalid-feedback">
                    <?= $errors['username'] ?>
                </div>
            </div>
            <div class="col-md-4 mb-3">
                <label for="email"><b>Email</b></label>
                <input <?= $class['email'] ?> type="email" id="email">
                <div class="invalid-feedback">
                    <?= $errors['email'] ?>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-4 mb-3">
                <label for="password"><b>Password</b></label>
                <input <?= $class['password'] ?> type="password" name="password" id="password" required>
                <div class="invalid-feedback">
                    <?= $errors['password'] ?>
                </div>
            </div>
            <div class="col-md-4 mb-3">
                <label for="repeat_password"><b>Repeat Password</b></label>
                <input <?= $class['password'] ?> type="password" name="repeat_password" id="repeat_password" required>
                <div class="invalid-feedback">
                    <?= $errors['password'] ?>
                </div>
            </div>
        </div>

        <input type="submit" name="submit" value="Sign Up" class="btn">
    </fieldset>
</form>

<?php
require __DIR__.'/../common/footer.phtml';
?>
