<?php
require __DIR__.'/../common/header.phtml';
require __DIR__.'/../common/topnavbar.phtml';
?>
    <form action="" method="post">
        <div class="container" style="padding: 0 300px">
            <div class="shadow px-5 rounded bg-transparent" style="margin: 180px 0 300px 0">
                <h2 class="py-4">Reset password</h2>

                <div class="input-group form-group mb-4">
                    <div class="input-group-prepend">
                        <span class="input-group-text bg-warning"><i class="fas fa-envelope"></i></span>
                    </div>
                    <?php if (!empty($errors['email'])) : ?>
                        <input class="form-control is-invalid" type="email" placeholder="Enter Email" name="email" required>
                    <?php endif; ?>
                    <?php if (empty($errors['email'])) : ?>
                        <input class="form-control" type="email" placeholder="Enter Email" name="email" value="<?= $data['email'] ?>" required>
                    <?php endif;
                    if (!empty($errors['email'])) : ?>
                        <div class="invalid-feedback">
                            <?=$errors['email']?>
                        </div>
                    <?php endif; ?>
                </div>

                <div class="d-flex justify-content-between mb-4">
                    <div>
                        <button class="btn btn-info px-4" type="submit">Sent password reset link</button>
                    </div>
                </div>
                <div class="text-center pb-4">
                    <span>I know my password! <a class="text-info text-decoration-none" href="<?= $url ?>auth/login">Sign In</a></span>
                </div>
            </div>
        </div>
    </form>


<?php
require __DIR__.'/../common/footer.phtml';
?>