<?php
require __DIR__.'/../common/header.phtml';
require __DIR__.'/../common/topnavbar.phtml';
require __DIR__.'/../common/messages.phtml';
?>

    <form action="" method="post">
        <div class="container">
            <label for="new_password">New password</label>
            <input type="password" placeholder="Enter your new password" name="new_password"  id="new_password" required>

            <label for="repeat_password">Repeat Password</label>
            <input type="password" placeholder="Repeat your new password" name="repeat_password" id="repeat_password" required>

            <input type="submit" name="submit" value="Reset" class="btn">
        </div>
    </form>

<?php
require __DIR__.'/../common/footer.phtml';
?>