<?php
require __DIR__.'/../common/header.phtml';
require __DIR__.'/../common/topnavbar.phtml';
?>
    <!doctype html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Home</title>
    </head>
    <body>
        <form method="post" action="/default/index"  class="col-lg-6 offset-lg-3">
            <h1>Search for a car</h1>
            <div class="input-field col s12">
                <select class="browser-default" name="make" required>
                    <option value="" disabled selected>Select Make</option>
                    <?php  foreach ($allMakes as $make) { ?>
                        <option value="<?= $make['id'] ?>"><?= $make['name'] ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="input-field col s12">
                <select class="browser-default" name="model" required>
                    <option value="" disabled selected>Select Model</option>
                    <?php  foreach ($allModels as $model) { ?>
                        <option value="<?= $model['id'] ?>"><?= $model['name'] ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="input-field col s12">
                <select class="browser-default" name="first_registration" required>
                    <option value="" disabled selected>Select First Registration</option>
                    <?php  foreach ($firstRegistrationArray as $firstRegistration) { ?>
                        <option value="<?= $firstRegistration ?>"><?= $firstRegistration ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="input-field col s12">
                <select class="browser-default" name="transmission" required>
                    <option value="" disabled selected>Select Transmission</option>
                    <?php  foreach ($transmissionArray as $transmission) { ?>
                        <option value="<?= $transmission ?>"><?= $transmission ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="input-field col s12">
                <button class="btn btn-primary">Search</button>
            </div>
        </form>


        <div class="col s12 m7">
            <h2 class="header">Results</h2>
                <?php foreach ($searchResult as $result) { ?>
                    <div class="card horizontal">
                        <div class="card-stacked">
                            <div class="card-content">
                                <p>Make - <?= $result['makename'] ?></p>
                            </div>
                            <div class="card-content">
                                <p>Model - <?= $result['modelname'] ?></p>
                            </div>
                            <div class="card-content">
                                <p>First Registration - <?= $result['first_registration'] ?></p>
                            </div>
                            <div class="card-content">
                                <p>Transmission - <?= $result['transmission'] ?></p>
                            </div>
                            <div class="card-action">
                                <a href="/cars/update?id=<?= $result['id']?>">This is a link to the car</a>
                            </div>
                        </div>
                    </div>
                <?php } ?>
        </div>
    </body>
    </html>

<?php
require __DIR__.'/../common/footer.phtml';
?>