<?php
require __DIR__.'/../common/header.phtml';
require __DIR__.'/../common/topnavbar.phtml';
var_dump($person['data']);
?>

<div class="container">
    <div>
        <div>
            <img src="<?= $person['data']['avatar'] ?>" alt="">
        </div>
        <div>
            <p><?= $person['data']['email'] ?></p>
            <p><?= $person['data']['first_name'] . ' ' . $person['data']['last_name'] ?></p>
        </div>
    </div>
    <div class="mr-3">
        <form action="../../Controllers/PersonController.php" method="get">
            <a href="<?= $url ?>/person/getperson/<?= $value['id'] ?>" class="btn btn-info mr-3">View</a>
        </form>
        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#staticBackdrop">Delete</button>
    </div>
    <div style="margin-top: 300px" class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Delete</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you shure you want to delete this?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form action="<?=$baseUrl?>person/delete/<?= $data['id'] ?>" name="delete" method="POST" >
                        <button type="submit" class="btn btn-info">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<?php
require __DIR__.'/../common/footer.phtml';
?>

