<?php
require __DIR__.'/../common/header.phtml';
require __DIR__.'/../common/topnavbar.phtml';
?>

    <!doctype html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Users Listing</title>
        <h1 class="offset-lg-6">Create user</h1>
    </head>
    <body>
    <div class="container">
        <div class="row">
            <div class="col-lg-10">
                <form action="/users/create" method="post">
                    <label for="first_name">First Name:</label>
                    <input type="text" name="first_name" id="first_name">

                    <label for="last_name">Last Name:</label>
                    <input type="text" name="last_name" id="last_name">

                    <label for="email">Email:</label>
                    <input type="text" name="email" id="email">

                    <input type="submit" name="create" value="Create">
                </form>
            </div>
        </div>
    </div>
    </body>
    </html>

<?php
require __DIR__.'/../common/footer.phtml';
?>