<?php
require __DIR__.'/../common/header.phtml';
require __DIR__.'/../common/topnavbar.phtml';
?>

    <!doctype html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Users Listing</title>
        <h1 class="offset-6">Users Listing</h1>

    </head>
    <body>
        <?php foreach ($users as $user) { ?>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-2">
                            <img src="<?= $user->avatar?>" alt="user photo">
                        </div>
                        <div class="col-lg-9">
                            First Name: <h6><?= $user->first_name?></h6>
                            Last Name: <h6><?= $user->last_name?></h6>
                            Email: <h6><?= $user->email?></h6>
                        </div>
                        <div class="col-lg-1">
                            <a href="<?= 'getUserById?id='. $user->id ?>">Edit</a>
                            <a href="<?= 'delete?id='. $user->id ?>">Delete</a>
                        </div>
                    </div>
                </div>
        <?php } ?>
    </body>
    </html>

<?php
require __DIR__.'/../common/footer.phtml';
?>