<?php
require __DIR__.'/../common/header.phtml';
require __DIR__.'/../common/topnavbar.phtml';

var_dump($users);
?>

    <!doctype html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Users Listing</title>
        <h1 class="offset-lg-6">User # <?= $users->id?></h1>
    </head>
    <body>
    <div class="container">
        <div class="row">
            <div class="col-lg-2">
                <img src="<?= $users->avatar?>" alt="user photo">
            </div>
            <div class="col-lg-10">
                <form action="/users/update" method="post">
                    <input type="hidden" name="id" id="id" value="<?= $users->id ?>">
                    <input type="hidden" name="avatar" id="avatar" value="<?= $users->avatar ?>">

                    <label for="first_name">First Name:</label>
                    <input type="text" name="first_name" id="first_name" value="<?= $users->first_name ?>">

                    <label for="last_name">Last Name:</label>
                    <input type="text" name="last_name" id="last_name" value="<?= $users->last_name ?>">

                    <label for="email">Email:</label>
                    <input type="text" name="email" id="email" value="<?= $users->email ?>">

                    <input type="submit" name="update" value="Update">
                </form>
            </div>
        </div>
    </div>
    </body>
    </html>

<?php
require __DIR__.'/../common/footer.phtml';
?>