<?php
require __DIR__.'/../common/header.phtml';
require __DIR__.'/../common/topnavbar.phtml';
?>

<form action="/cars/create" class="col-lg-6 offset-lg-3" method="POST">
    <h2>Create car</h2>
    <div class="input-field col s6">
        <select class="browser-default" name="make" required>
            <option value="" disabled selected>Select Make</option>
            <?php  foreach ($allMakes as $make) { ?>
                <option value="<?= $make['id'] ?>"><?= $make['name'] ?></option>
            <?php } ?>
        </select>
    </div>

    <div class="input-field col s12">
        <select class="browser-default" name="model" required>
            <option value="" disabled selected>Select Model</option>
            <?php  foreach ($allModels as $model) { ?>
                <option value="<?= $model['id'] ?>"><?= $model['name'] ?></option>
            <?php } ?>
        </select>
    </div>
    <div class="input-field col s12">
        <select class="browser-default" name="first_registration" required>
            <option value="" disabled selected>Select First Registration</option>
            <?php  foreach ($firstRegistrationArray as $firstRegistration) { ?>
                <option value="<?= $firstRegistration ?>"><?= $firstRegistration ?></option>
            <?php } ?>
        </select>
    </div>
    <div class="input-field col s12">
        <select class="browser-default" name="transmission" required>
            <option value="" disabled selected>Select Transmission</option>
            <?php  foreach ($transmissionArray as $transmission) { ?>
                <option value="<?= $transmission ?>"><?= $transmission ?></option>
            <?php } ?>
        </select>
    </div>

    <input type="submit" value="Create" class="btn btn-primary">
</form>

<?php
require __DIR__.'/../common/footer.phtml';
?>

