<?php
require __DIR__.'/../common/header.phtml';
require __DIR__.'/../common/topnavbar.phtml';
?>

<form action="/cars/update" method="POST" class="col-lg-6 offset-lg-3">
    <h2>Edit car</h2>
    <input type="text" hidden id="id" name="id" value="<?= $car['id'] ?? '' ?>">

    <div class="input-field col s6">
        <select class="browser-default" name="make">
            <option value="" disabled>Select Make</option>
            <?php  foreach ($allMakes as $make) { ?>
                <option value="<?= $make['id'] ?>" <?= ($car['make_id'] == $make['id']) ? 'selected' : ''?>><?= $make['name'] ?></option>
            <?php } ?>
        </select>
    </div>
    <div class="input-field col s12">
        <select class="browser-default" name="model" id="model">
            <option value="" disabled>Select Model</option>
            <?php  foreach ($allModels as $model) { ?>
                <option value="<?= $model['id'] ?>" <?= $car['model_id'] == $model['id'] ? 'selected' : '' ?>><?= $model['name'] ?></option>
            <?php } ?>
        </select>
    </div>
    <div class="input-field col s12">
        <select class="browser-default" name="first_registration">
            <option value="" disabled>Select First Registration</option>
            <?php  foreach ($firstRegistrationArray as $firstRegistration) { ?>
                <option value="<?= $firstRegistration ?>" <?= ($car['first_registration'] == $firstRegistration) ? 'selected' : '' ?>><?= $firstRegistration ?></option>
            <?php } ?>
        </select>
    </div>
    <div class="input-field col s12">
        <select class="browser-default" name="transmission">
            <option value="" disabled>Select Transmission</option>
            <?php  foreach ($transmissionArray as $transmission) { ?>
                <option value="<?= $transmission ?>" <?= ($car['transmission'] == $transmission) ? 'selected' : '' ?>><?= $transmission ?></option>
            <?php } ?>
        </select>
    </div>

    <input type="submit" value="Update" class="btn btn-primary">
</form>

<?php
require __DIR__.'/../common/footer.phtml';
?>
