<?php
require __DIR__.'/../common/header.phtml';
require __DIR__.'/../common/topnavbar.phtml';
?>

<h2>Edit car</h2>

<form action="/cars/update" class="col" method="POST">
    <input type="text" hidden id="id" name="id" value="<?= $car['id'] ?? '' ?>">

    <label for="make">Make</label>
    <input id="make" type="text" class="validate" name="make" value="<?= $car['make'] ?? ''?>">

    <label for="model">Model</label>
    <input id="model" type="text" class="validate" name="model" value="<?= $car['model'] ?? ''?>">

    <label for="first_registration">First Registration</label>
    <input id="first_registration" type="text" class="validate" name="first_registration" value="<?= $car['first_registration'] ?? ''?>">

    <label for="transmission">Transmission</label>
    <input id="transmission" type="text" class="validate" name="transmission" value="<?= $car['transmission'] ?? ''?>">

    <input type="submit" value="Update" class="btn">
</form>

<?php
require __DIR__.'/../common/footer.phtml';
?>
