</body>
<footer class="page-footer">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Cars Pancho</h5>
                <img src="/logo.jpg" alt="logo" width="80" height="80">
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                    <li><a class="grey-text text-lighten-3" href="/">Home</a></li>
                    <li><a class="grey-text text-lighten-3" href="/cars/listing">Cars Listing</a></li>
                    <?php if ($this->isLoggedIn()):  ?>
                        <li><a class="grey-text text-lighten-3" href="/cars/create">Cars Create</a></li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            © 2022 Copyright Text
        </div>
    </div>
</footer>
</html>