<div style="background-color: #17a2b8; padding: 40px 0" class="">
    <div class="container">
        <div class="d-flex justify-content-between align-items-center">
            <p style="margin: 0" class="text-light">carsite@gmail.com</p>
            <div>
                <i class="fab fa-facebook-square text-light"></i>
                <i class="fab fa-instagram text-light"></i>
                <i class="fab fa-twitter text-light"></i>
            </div>
        </div>
    </div>
</div>
</body>
</html>